title: Mark Pasacreta
description: Engineering portfolio of Mark Pasacreta
url: "https://markpasacreta.com"
baseurl: ""

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      back_url: /portfolio/

exclude:
  - README.md
  - design_handoff_portfolio_site
